# Generated by Django 4.1.5 on 2023-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='complete',
        ),
    ]
